angular.module('stockDogApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/dashboard.html',
    "<div class=\"row\"> <!-- Left Column --> <div class=\"col-md-3\"> <stk-watchlist-panel></stk-watchlist-panel> </div> <!-- Right Column --> <div class=\"col-md-9\"> <div class=\"panel panel-info\"> <div class=\"panel-heading\"> <span class=\"glyphicon glyphicon-globe\"></span> Portfolio Overview </div> <div class=\"panel-body\"> <div ng-hide=\"watchlists.length && watchlists[0].stocks.length\" class=\"jumbotron\"> <h1>Unleash the hounds!</h1> <p> StockDog, your personal investment watchdog, is ready to be set loose on the financial markets! </p> <p>Create a watchlist and add some stocks to begin monitoring.</p> </div> <div ng-show=\"watchlists.length && watchlists[0].stocks.length\"> <!-- Top Row --> <div class=\"row\"> <!-- Left Column --> <div class=\"col-md-6\"> <div stk-sign-fade=\"{{marketValue}}\" class=\"well\"> <h2>{{marketValue | currency}}</h2> <h5>Total Market Value</h5> </div> </div> <!-- Right Column --> <div class=\"col-md-6\"> <div class=\"well\" stk-sign-color=\"{{dayChange}}\"> <h2>{{dayChange | currency}}</h2> <h5>Total Day Change</h5> </div> </div> </div> <!-- Bottom Row --> <div class=\"row\"> <!-- Left Column --> <div class=\"col-md-6\"> <div google-chart chart=\"donutChart\" style=\"{{cssStyle}}\"></div> </div> <!-- Right Column --> <div class=\"col-md-6\"> <div google-chart chart=\"columnChart\" style=\"{{cssStyle}}\"></div> </div> </div> </div> </div> </div> </div> </div>"
  );


  $templateCache.put('views/templates/addlist-modal.html',
    "<div class=\"modal\" tabindex=\"-1\" role=\"dialog\"> <div class=\"modal-dialog\"> <div class=\"modal-content\"> <div class=\"modal-header\"> <!-- [1] Invoke $modal.$hide() on click --> <button type=\"button\" class=\"close\" ng-click=\"$hide()\">&times; </button> <h4 class=\"modal-title\">Create New Watchlist</h4> </div> <!-- [2] Name this form for validation purposes --> <form role=\"form\" id=\"add-list\" name=\"listForm\"> <div class=\"modal-body\"> <div class=\"form-group\"> <label for=\"list-name\">Name</label> <!-- [3] Bind input to watchlist.name --> <input type=\"text\" class=\"form-control\" id=\"list-name\" placeholder=\"Name this watchlist\" ng-model=\"watchlist.name\" required> </div> <div class=\"form-group\"> <label for=\"list-description\">Brief Description</label> <!-- [4] Bind input to watchlist.description --> <input type=\"text\" class=\"form-control\" id=\"list-description\" maxlength=\"40\" placeholder=\"Describe this watchlist\" ng-model=\"watchlist.description\" required> </div> </div> <div class=\"modal-footer\"> <!-- [5] Create list on click, but disable if form is invalid --> <button type=\"submit\" class=\"btn btn-success\" ng-click=\"createList()\" ng-disabled=\"!listForm.$valid\">Create</button> <button type=\"button\" class=\"btn btn-danger\" ng-click=\"$hide()\">Cancel</button> </div> </form> </div> </div> </div>"
  );


  $templateCache.put('views/templates/addstock-modal.html',
    "<div class=\"modal\" tabindex=\"-1\" role=\"dialog\"> <div class=\"modal-dialog\"> <div class=\"modal-content\"> <div class=\"modal-header\"> <button type=\"button\" class=\"close\" ng-click=\"$hide()\">&times;</button> <h4 class=\"modal-title\">Add New Stock</h4> </div> <form role=\"form\" id=\"add-stock\" name=\"stockForm\"> <div class=\"modal-body\"> <div class=\"form-group\"> <label for=\"stock-symbol\">Symbol</label> <input type=\"text\" class=\"form-control\" id=\"stock-symbol\" placeholder=\"Stock Symbol\" ng-model=\"newStock.company\" bs-options=\"company as company.label for company in companies\" bs-typeahead required> </div> <div class=\"form-group\"> <label for=\"stock-shares\">Shares Owned</label> <input type=\"number\" class=\"form-control\" id=\"stock-shares\" placeholder=\"# Shares Owned\" ng-model=\"newStock.shares\" required> </div> </div> <div class=\"modal-footer\"> <button type=\"submit\" class=\"btn btn-success\" ng-click=\"addStock()\" ng-disabled=\"!stockForm.$valid\">Add</button> <button type=\"button\" class=\"btn btn-danger\" ng-click=\"$hide()\">Cancel</button> </div> </form> </div> </div> </div>"
  );


  $templateCache.put('views/templates/stock-table.html',
    "<table class=\"table\"> <thead> <tr> <td>Symbol</td> <td>Shares Owned</td> <td>Last Price</td> <td>Price Change <span> ( <span ng-disabled=\"showPercent === false\"> <a ng-click=\"showPercent = !showPercent\">$</a> </span>| <span ng-disabled=\"showPercent === true\"> <a ng-click=\"showPercent = !showPercent\">%</a> </span>) </span> </td> <td>Market Value</td> <td>Day Change</td> </tr> </thead> <tfoot ng-show=\"watchlist.stocks.length > 1\"> <tr> <td>Totals</td> <td>{{watchlist.shares}}</td> <td></td> <td></td> <td stk-sign-fade=\"{{watchlist.marketValue}}\">{{watchlist.marketValue | currency}}</td> <td stk-sign-color=\"{{watchlist.dayChange}}\">{{watchlist.dayChange | currency}}</td> </tr> </tfoot> <tbody> <tr stk-stock-row ng-repeat=\"stock in watchlist.stocks track by $index\" stock=\"stock\" is-last=\"$last\"> <td>{{stock.company.symbol}}</td> <td contenteditable type=\"number\" ng-model=\"stock.shares\"></td> <td stk-sign-fade=\"{{stock.lastPrice}}\">{{stock.lastPrice | currency}}</td> <td stk-sign-color=\"{{stock.change}}\"> <span ng-hide=\"showPercent\">{{stock.change}}</span> <span ng-show=\"showPercent\">{{stock.percentChange}}</span> </td> <td>{{stock.marketValue | currency}}</td> <td stk-sign-color=\"{{stock.dayChange}}\">{{stock.dayChange | currency}} <button type=\"button\" class=\"close\" ng-click=\"removeStock(stock)\">&times;</button> </td> </tr> </tbody> </table> <div class=\"small text-center\">Click on Shares Owned cell to edit.</div>"
  );


  $templateCache.put('views/templates/watchlist-panel.html',
    "<div class=\"panel panel-info\"> <div class=\"panel-heading\"> <span class=\"glyphicon glyphicon-eye-open\"></span> Watchlists <!-- Invoke showModal() handler on click --> <button type=\"button\" class=\"btn btn-success btn-xs pull-right\" ng-click=\"showModal()\"> <span class=\"glyphicon glyphicon-plus\"></span> </button> </div> <div class=\"panel-body\"> <!-- Show help text if no watchlists exist --> <div ng-if=\"!watchlists.length\" class=\"text-center\"> Use <span class=\"glyphicon glyphicon-plus\"></span> to create a list </div> <div class=\"list-group\"> <!-- Repeat over each list in watchlists and create link --> <a class=\"list-group-item\" ng-class=\"{ active: currentList == list.id }\" ng-repeat=\"list in watchlists track by $index\" ng-click=\"gotoList(list.id)\"> {{list.name}} <!-- Delete this list by invoking deleteList() handler --> <button type=\"button\" class=\"close\" ng-click=\"deleteList(list)\">&times; </button> </a> </div> </div> </div>"
  );


  $templateCache.put('views/watchlist.html',
    "<div class=\"row\"> <!-- Left Column --> <div class=\"col-md-3\"> <stk-watchlist-panel></stk-watchlist-panel> </div> <!-- Right Column --> <div class=\"col-md-9\"> <div class=\"panel panel-info\"> <div class=\"panel-heading\"> <span class=\"glyphicon glyphicon-list\"></span> {{watchlist.description}} <button type=\"button\" class=\"btn btn-success btn-xs pull-right\" ng-click=\"showStockModal()\"> <span class=\"glyphicon glyphicon-plus\"></span> </button> </div> <div class=\"panel-body table-responsive\"> <div ng-hide=\"stocks.length\" class=\"jumbotron\"> <h1>Woof.</h1> <p>Looks like you haven't added any stocks to this watchlist yet!</p> <p>Do so now by clicking the <span class=\"glyphicon glyphicon-plus\"></span> located above.</p> </div> <!-- loop over all stocks and display company symbols --> <stk-stock-table ng-show=\"stocks.length\" watchlist=\"watchlist\"> </stk-stock-table></div> </div> </div> </div>"
  );

}]);
